CREATE DATABASE DSA_PROJECT_DB

SELECT * FROM KMS_DB

1------PRODUCT CATEGORY WITH THE HIGHEST SALES------

SELECT TOP 1 PRODUCT_CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM KMS_DB
GROUP BY PRODUCT_CATEGORY
ORDER BY SUM(SALES)


2---- THE TOP 3 REGION IN TERMS OF SALES----

SELECT TOP 3 REGION, SUM(SALES) AS TOTAL_SALES
FROM KMS_DB
GROUP BY REGION
ORDER BY TOTAL_SALES DESC


-----BOTTOM 3 REGION IN TERMS OF SALES---

SELECT TOP 3 REGION, SUM(SALES) AS TOTAL_SALES
FROM KMS_DB
GROUP BY REGION
ORDER BY TOTAL_SALES ASC


3----TOTAL SALES OF APPLIANCES IN ONTARIO-----

 SELECT SUM(SALES) AS TOTAL_SALES
 FROM KMS_DB
 WHERE PRODUCT_CATEGORY = 'APPLIANCES' AND REGION = 'ONTARIO'


 4-----ADVICE FOR INCREASING REVENUE FROM BOTTOM 10 CUSTOMERS------

 SELECT TOP 10 CUSTOMER_NAME, SUM(SALES) AS TOTAL_SALES
 FROM KMS_DB
 GROUP BY CUSTOMER_NAME
 ORDER BY TOTAL_SALES ASC

 The potential strategies for incrasing revenue from bottom 10 customers are: targeted market, loyalty programs 
 and personalized offers or improving cutomer services

 5----SHIPPING METHOD WITH THE HIGHEST COST------

 SELECT TOP 1 SHIP_MODE, SUM (SHIPPING_COST) AS TOTAL_COST
 FROM KMS_DB
 GROUP BY SHIP_MODE
 ORDER BY TOTAL_COST DESC

 CASE SCENERIO II
6-----MOST VALUABLE TOP 10 CUSTOMERS AND PRODUCT/SERVICES-----

 SELECT TOP 10 CUSTOMER_NAME, SUM(SALES) AS TOTAL_SALES
 FROM KMS_DB
 GROUP BY CUSTOMER_NAME
 ORDER BY TOTAL_SALES DESC

 SELECT TOP 10 CUSTOMER_NAME, PRODUCT_NAME, SUM(SALES ) AS TOTAL_SALES
 FROM KMS_DB
 GROUP BY CUSTOMER_NAME, PRODUCT_NAME
 ORDER BY TOTAL_SALES DESC


7 -----SMALL BUSINESS CUSTOMER WITH HIGHEST SALES-----

 SELECT TOP 1 CUSTOMER_NAME, SUM(SALES) AS TOTAL_SALES
 FROM KMS_DB
 WHERE CUSTOMER_SEGMENT = 'SMALL BUSINES'
 GROUP BY CUSTOMER_NAME
 ORDER BY TOTAL_SALES DESC


 8------CORPORATE CUSTOMER WITH MOST ORDERS-------
 
 SELECT TOP 1 CUSTOMER_NAME, COUNT(ORDER_ID) AS TOTAL_ORDERS
 FROM KMS_DB
 WHERE CUSTOMER_SEGMENT = 'CORPORATE'
 GROUP BY CUSTOMER_NAME
 ORDER BY TOTAL_ORDERS DESC


 9-----MOST PROFITABLE CONSUMER CUSTOMER-------

 SELECT TOP 1 CUSTOMER_NAME, SUM(PROFIT) AS TOTAL_PROFIT
 FROM KMS_DB
 WHERE CUSTOMER_SEGMENT = 'CONSUMER'
 GROUP BY CUSTOMER_NAME
 ORDER BY TOTAL_PROFIT DESC


 10-----CUSTOMERS WHO RETURNED ITEMS AND THEIR SEGMENT-----

 SELECT CUSTOMER_NAME, CUSTOMER_SEGMENT
 FROM KMS_DB
 WHERE ORDER_ID IN (SELECT ORDER_ID FROM KMS_DB WHERE SALES < 0)


 11-----APPROPRIATENESS OF SHIPPING COSTS BASED ON ORDER PRIORITY------

 SELECT SHIP_MODE, AVG(SHIPPING_COST) AS AVG_COST, SUM(SALES) AS TOTAL_SALES
 FROM KMS_DB
 GROUP BY SHIP_MODE
 ORDER BY AVG_COST DESC
  








  
